spring.application.name=bankwithdrawal
spring.datasource.url=jdbc:h2:mem:dcbapp
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
aws.region=us-east-1
aws.sns.endpoint=http://localhost:4566
aws.accessKeyId=local
aws.secretAccessKey=local